# Generated by Django 4.2.1 on 2023-05-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatorsmodel',
            name='maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
