# Generated by Django 4.2.1 on 2023-05-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_elevatorsmodel_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatorsmodel',
            name='current_floor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
