# Generated by Django 4.2.1 on 2023-05-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0003_elevatorsmodel_current_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequestmodels',
            old_name='floor',
            new_name='current_floor',
        ),
    ]
