# Generated by Django 4.2.1 on 2023-05-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0005_alter_userrequestmodels_current_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatorsmodel',
            name='door',
            field=models.CharField(choices=[('OPEN', 'opened'), ('close', 'closed')], default='closed', max_length=10),
            preserve_default=False,
        ),
    ]
