# Generated by Django 4.2.1 on 2023-05-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0006_elevatorsmodel_door'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevatorsmodel',
            name='door',
            field=models.CharField(choices=[('OPEN', 'opened'), ('CLOSE', 'closed')], max_length=10),
        ),
    ]
