# Generated by Django 4.2.1 on 2023-05-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0007_alter_elevatorsmodel_door'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatorsmodel',
            name='first_floor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elevatorsmodel',
            name='last_floor',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
